#!/bin/sh
set -ev
yum install -y git cmake pulseaudio \
  alsa-lib-devel pulseaudio-libs-devel jack-audio-connection-kit-devel \
  libvorbis-devel opusfile-devel libsndfile-devel
pulseaudio --start

pip install cmake>=3.13
git clone --depth 1 https://github.com/kcat/openal-soft
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -S openal-soft -B openal-soft/build
cmake --build openal-soft/build --parallel `nproc` --target install

git clone --depth 1 https://github.com/kcat/alure
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -S alure -B alure/build
cmake --build alure/build --parallel `nproc` --target install
pip uninstall -y cmake
