#!/bin/sh
set -ev
git clone --depth 1 https://github.com/kcat/alure /tmp/alure
cd /tmp/alure/build
OPENALDIR=$(brew --prefix openal-soft) cmake -DCMAKE_FIND_FRAMEWORK=NEVER ..
cmake --build . --config Release
sudo cmake --install .
