#!/bin/sh
set -ex
git clone --depth 1 https://github.com/kcat/alure /tmp/alure
OPENALDIR=$(brew --prefix openal-soft) cmake -DCMAKE_FIND_FRAMEWORK=NEVER \
  -S /tmp/alure -B /tmp/alure/build
sudo cmake --build /tmp/alure/build --parallel $(sysctl -n hw.ncpu) \
  --config Release --target install
